[build-system]
requires = ["maturin>=1.8.0"]
build-backend = "maturin"

[project]
name = "color_palette_extract"
requires-python = ">=3.9"
classifiers = ["Programming Language :: Rust"]

[tool.maturin]
manylinux = "2_35"
